const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = relative => fs.readFileSync(path.join(root, relative), "utf8");
const portal = read("public/app.js");
const catalog = read("server/index.js");

assert.match(catalog, /hex_code,collection,instructions/);
assert.match(catalog, /hexCode: color\.hex_code \|\| ""/);
assert.match(catalog, /collection: color\.collection === "CORE" \? "CORE" : "SEASONAL"/);
assert.match(catalog, /\/api\/client\/colors\/:id\/collection/);
assert.match(portal, /setInterval\(\(\)=>show\(\(index\+1\)%slides\.length\),900\)/);
assert.match(portal, /data-card-collection="CORE"/);
assert.doesNotMatch(portal, /card-menu-head|kept every season|this season only/);
assert.doesNotMatch(read("public/color-details.css"), /\.card-menu-head/);
assert.match(portal, /data-card-copy-hex/);
assert.match(portal, /class="core-banner">Core</);
assert.match(portal, /data-card-save/);
assert.match(portal, /Approved colors/);
assert.match(portal, /Core colors/);
assert.match(portal, /Seasonal colors/);
assert.match(portal, /value="CORE">Core/);
assert.match(portal, /placeholder="Search"/);
assert.match(portal, /class="search-field-icon"/);
assert.match(portal, /function colorSearchText/);
assert.doesNotMatch(portal, /Need approval|Needs approval|With approved references/);
assert.match(portal, /data-card-delete/);
assert.match(portal, /challenge:"delete"/);
assert.match(portal, /state\.user\?\.role==="ADMIN"/);
const deleteRoute = catalog.slice(catalog.indexOf('app.post("/api/client/colors/:id/delete"'), catalog.indexOf('app.post("/api/client/colors/:id/unarchive"'));
assert.match(deleteRoute, /requireRole\("ADMIN"\)/);
assert.match(deleteRoute, /confirmation !== "delete"/);
assert.match(read("public/index.html"), /id="modalDanger"/);
assert.match(portal, /dangerButton\.hidden=!danger/);
assert.match(portal, /Delete \$\{client\.name\}\?/);
assert.match(portal, /\/api\/admin\/clients\/\$\{client\.id\}\/delete/);
const clientDeleteRoute = catalog.slice(catalog.indexOf('app.post("/api/admin/clients/:id/delete"'), catalog.indexOf('app.get("/api/admin/filesystem"'));
assert.match(clientDeleteRoute, /requireRole\("ADMIN"\)/);
assert.match(clientDeleteRoute, /confirmation !== "delete"/);
assert.match(clientDeleteRoute, /DELETE FROM clients WHERE id=/);
assert.match(deleteRoute, /DELETE FROM color_requests WHERE color_id=/);
assert.doesNotMatch(deleteRoute, /assertLibraryEdit/);
assert.match(portal, /data-download-version/);
assert.match(portal, /function referenceDownloadName/);
assert.match(portal, /M6 3\.5 10\.5 8 6 12\.5/);
assert.match(portal, /Number\(Boolean\(b\.saved\)\)-Number\(Boolean\(a\.saved\)\)/);
assert.match(catalog, /\/api\/client\/colors\/:id\/save/);
assert.match(catalog, /withSavedColors/);
assert.match(read("database/009_color_saves.sql"), /CREATE TABLE IF NOT EXISTS color_saves/);
assert.match(portal, /\["Hex",color\.hexCode\],\["Pantone",color\.colorCode\]/);
assert.match(portal, /name="hexCode"/);
assert.match(portal, /Hex code <span class="muted" title="https:\/\/registry\.color\.org\/rgb-registry\/adobergb">Adobe RGB \(1998\)<\/span>/);
assert.match(portal, /\["Profile",color\.hexCode\?"Adobe RGB \(1998\)":""\]/);
assert.doesNotMatch(portal, /reference-editor-heading/);
assert.match(catalog, /hex_code=\$4,instructions=\$5/);
assert.doesNotMatch(portal, /id="copyHex"|hex-code-section/);
assert.match(portal, /id="colorPageNotes"/);
assert.doesNotMatch(portal, /function bindEditableNotes|id="colorInstructionsInput"|id="saveInlineNotes"/);
assert.match(portal, /<label>Pantone<input name="colorCode"/);
assert.doesNotMatch(portal, /Color code|Client color code/);
const referenceMarkup = portal.slice(portal.indexOf("function colorPageReferenceMarkup"), portal.indexOf("function notesIcon"));
assert.match(referenceMarkup, /data-download-version/);
assert.match(referenceMarkup, /referenceDownloadName\(color\?\.name/);
assert.match(referenceMarkup, /class="reference-download"/);
assert.match(referenceMarkup, /class="reference-status"/);
assert.match(referenceMarkup, /reference-download-label">Download</);
const colorPage = portal.slice(portal.indexOf("function renderColorPage"), portal.indexOf("function restrictLockedColorPage"));
assert.match(colorPage, /color\.collection==="CORE"\?`<span class="core-banner">Core<\/span>`/);
assert.match(colorPage, /downloadReferenceFile\(button\)/);
const lockedPage = portal.slice(portal.indexOf("function restrictLockedColorPage"), portal.indexOf("function decorateColorPageDetails"));
assert.doesNotMatch(lockedPage, /data-download-version/);
assert.doesNotMatch(colorPage, /Select a swatch to preview/);
assert.doesNotMatch(colorPage, /Reference types/);
assert.match(colorPage, /id="editRequestBottom"/);
assert.match(colorPage, /<div id="colorPreviewLink"[\s\S]*class="preview-caption"/);
assert.match(read("public/color-details.css"), /\.color-page-preview \{[^}]*padding: 0 2px 2px/);
assert.match(read("public/color-details.css"), /\.color-page-preview > \.preview-caption #previewKind,\s*\.request-stage > \.preview-caption #requestPreviewKind \{[^}]*font-size: 14px;[^}]*font-weight: 650/);
assert.match(read("public/color-details.css"), /\.color-page-preview > \.preview-caption #previewFilename,\s*\.request-stage > \.preview-caption #requestPreviewFilename \{[^}]*font-size: 12px;[^}]*font-weight: 400/);
assert.match(read("public/styles.css"), /\.request-stage\{display:grid;grid-template-rows:auto minmax\(0,1fr\);gap:2px;[^}]*padding:0 2px 2px/);
assert.match(read("public/color-details.css"), /\.color-page-preview \{[^}]*grid-template-rows: auto minmax\(0,1fr\)/);
assert.match(read("public/color-details.css"), /\.color-page-preview > \.preview-caption,\s*\.request-stage > \.preview-caption \{[^}]*order: -1/);
assert.match(colorPage, /<div id="colorPreviewLink"/);
assert.doesNotMatch(colorPage, /<a id="colorPreviewLink"/);
assert.match(colorPage, /id="previewOpenFull"/);
assert.match(colorPage, /id="previewZoomIn"/);
assert.match(colorPage, /id="previewNavigator"/);
assert.match(colorPage, /\/api\/display\/\$\{version\.id\}/);
assert.match(colorPage, /const thumb=`\/api\/previews\/\$\{version\.id\}`/);
assert.match(colorPage, /Loading full image/);
assert.match(catalog, /\/api\/display\/:versionId/);
assert.match(read("server/previews.js"), /function displayImage/);
assert.match(read("server/color-requests.js"), /\/deliveries\/:versionId\/display/);
assert.match(colorPage, /target="_blank"/);
assert.match(portal, /function bindColorPreview/);
assert.match(portal, /function previewNavigatorRect/);
assert.doesNotMatch(colorPage, /aria-label="Open preview image in a new tab"/);
assert.match(portal, /function colorPageReferences\(color\)/);
assert.match(portal, /reference\.kind==="QUICK"\?0:reference\.kind==="FULL"\?1:2/);
assert.match(portal, /if\(!node\.childElementCount\)node\.remove\(\)/);
assert.match(read("public/color-details.css"), /\.color-page-reference \.detail-reference-actions:empty \{ display: none; \}/);
assert.match(read("public/color-details.css"), /\.color-preview-link > \.preview-zoom,\s*\.color-preview-link > \.preview-actions \{ opacity: 0; pointer-events: none; \}/);
assert.match(portal, /function previewActionBar/);
assert.match(portal, /previewActionBar\(full\)/);
assert.match(portal, /compare = false/);
assert.match(portal, /id="previewCompare"/);
assert.match(portal, /preview-compare-pick/);
assert.match(portal, /data-compare-short="V\$\{version\.number\}"/);
assert.match(read("public/color-details.css"), /\.color-preview-link\.is-comparing \.preview-open-hint \{ display: none; \}/);
assert.match(portal, /class="preview-compare-tip">Exit compare/);
assert.match(portal, /aria-label", "Exit compare"/);
assert.match(portal, /aria-pressed"\) === "true"\) setPreviewCompare\(false\)/);
assert.match(read("public/color-details.css"), /\.preview-compare-tip/);
assert.match(read("public/color-details.css"), /\.preview-compare-check/);
assert.match(portal, /function syncCompareZoom/);
assert.match(portal, /previewCompareZoomAt\(compareZoom\.zoom/);
assert.match(portal, /layer\.addEventListener\("pointermove", move\)/);
assert.match(read("public/color-details.css"), /\.preview-compare-clip > \.preview-compare-over/);
assert.match(read("public/color-details.css"), /\.color-preview-link:hover > \.preview-zoom/);
assert.match(read("public/color-details.css"), /\.color-preview-viewport:has\(> img\.is-fitted\) \{ cursor: zoom-in; \}/);
assert.match(read("public/color-details.css"), /\.library-color-card \.card-save,\s*\.library-color-card \.card-menu-button \{[^}]*radial-gradient\(circle, rgba\(0,0,0,\.58\) 0%, rgba\(0,0,0,\.42\) 48%, rgba\(0,0,0,\.16\) 72%, rgba\(0,0,0,0\) 94%\)/);
assert.match(portal, /title\.textContent=type/);
assert.match(read("UXP/main.js"), /<span>Pantone<\/span>/);
assert.match(read("UXP/main.js"), /<span>Hex<\/span>/);
assert.match(read("UXP/catalog.js"), /hexCode: color\.hexCode \|\| ""/);

console.log("Color detail identity tests passed.");
