const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("UXP/index.html", "utf8");
const js = fs.readFileSync("UXP/main.js", "utf8");
const css = fs.readFileSync("UXP/styles.css", "utf8");

const pluginConfig = fs.readFileSync("UXP/config.js", "utf8");
const manifest = fs.readFileSync("UXP/manifest.json", "utf8");
const permissions = JSON.parse(manifest).requiredPermissions;
assert.equal(JSON.parse(manifest).version, "0.5.11");
assert.equal(permissions.network.domains, "all");
assert.equal(permissions.webview.allow, "yes");
assert.equal(permissions.webview.domains, "all");
assert.equal(permissions.webview.enableMessageBridge, "localAndRemote");
assert.equal(JSON.parse(manifest).host.minVersion, "22.5.0");
assert.doesNotMatch(pluginConfig, /pluginAccessKey/);
assert.doesNotMatch(pluginConfig, /filenamePrefixes/);
assert.doesNotMatch(pluginConfig, /searchAliases/);
assert.match(js, /createPortalClient/);
assert.match(fs.readFileSync("UXP/portal-client.js", "utf8"), /function xhrFetch/);
assert.match(js, /createWebviewBridge/);
assert.match(js, /portalBridge\.connect/);
assert.match(js, /session\.hydrate/);
assert.match(js, /session\.attachLocal/);
assert.match(js, /scheduleAttachLocal/);
assert.match(js, /limit: 8/);
assert.doesNotMatch(js, /setBusy\(false\);\s*\n\s*\}\s*\n\s*try \{/);
assert.match(js, /orderedConnectHosts/);
assert.match(js, /rememberPreferredHost/);
assert.match(js, /copyPluginFileToTemp/);
assert.match(js, /xhrFetch/);
assert.doesNotMatch(js, /fetchImpl: fetch/);
assert.doesNotMatch(fs.readFileSync("UXP/portal-client.js", "utf8"), /AbortSignal/);
assert.match(js, /ensureLanBridge/);
assert.match(js, /startLanBridgeHelper/);
assert.equal(permissions.launchProcess.extensions.includes(".cmd"), true);
assert.ok(fs.existsSync("UXP/lan-bridge.vbs"));
assert.ok(fs.existsSync("UXP/lan-bridge.ps1"));
assert.ok(fs.existsSync("UXP/lan-bridge.cmd"));
assert.match(html, /id="portalWebview"/);
assert.match(fs.readFileSync("scripts/package-plugin.js", "utf8"), /"CSXS"/);
assert.match(js, /connectionHosts\(studio\.serverUrls, config\.portalHosts\)/);
assert.doesNotMatch(js, /studio\.serverUrls\[0\]/);
assert.match(js, /createLibrarySession/);
assert.match(js, /createApprovedList/);
assert.doesNotMatch(html, /pluginKeyInput|Plugin key/);
assert.doesNotMatch(js, /showSetup\(|pluginKey/);
assert.match(js, /await boot\(\)/);
assert.match(html, /id="libraryTitle">Color Library</);
assert.match(js, /"Color Library"/);
assert.doesNotMatch(html, /Approved colors<\/h1>/);
assert.match(css, /\.search-control \{[^}]*overflow: hidden[^}]*border: 1px solid var\(--border\)[^}]*border-radius: 8px[^}]*background: var\(--surface-raised\)/);
assert.match(html, /<input id="searchInput" type="search" placeholder="Search colors"/);
assert.match(html, /<input id="swatchSearch" type="search" placeholder="Search swatches"/);
assert.doesNotMatch(html, /quiet/);
assert.doesNotMatch(html, /slot="label"/);
assert.match(css, /\.search-control \{[^}]*display: flex[^}]*align-items: center/);
assert.match(css, /\.search-control \{[^}]*height: calc\(var\(--control-height\) \+ 2px\)[^}]*border-bottom-color: var\(--border-strong\)/);
assert.match(css, /\.search-row \{[^}]*gap: 0/);
assert.match(css, /#searchInput, #swatchSearch \{[^}]*width: 100%[^}]*height: 100%[^}]*margin: 0[^}]*padding: 0[^}]*background: var\(--surface-raised\)/);
assert.match(css, /\.sort-control \{[^}]*margin-left: 8px/);
assert.match(css, /\.app-shell\.is-client-menu-open #searchInput,[\s\S]*visibility: hidden/);
assert.match(js, /classList\.toggle\("is-client-menu-open", shouldOpen\)/);
assert.match(css, /\.clear-search \{[^}]*position: absolute[^}]*right: 6px/);
assert.doesNotMatch(html, /<label[^>]*\sfor=/);
assert.doesNotMatch(html, /<select id="sortSelect"/);
assert.match(html, /id="sortSelect"[^>]*aria-haspopup="listbox"[^>]*aria-expanded="false"/);
assert.match(html, /id="sortMenu"[^>]*role="listbox"/);
assert.match(html, /class="sort-chevron"[^>]*>▼</);
assert.match(css, /\.sort-control \{[^}]*height: calc\(var\(--control-height\) \+ 2px\)/);
assert.match(css, /\.sort-control \{[^}]*z-index: 20/);
assert.match(css, /\.sort-menu \{[^}]*position: absolute[^}]*z-index: 30[^}]*top: calc\(100% \+ 5px\)[^}]*right: 0/);
assert.match(css, /\.app-shell\.is-sort-menu-open \.color-grid \{[^}]*overflow-y: hidden/);
assert.match(js, /classList\.toggle\("is-sort-menu-open", shouldOpen\)/);
assert.match(css, /\.sort-menu \{[^}]*background: var\(--surface-raised\)/);
assert.match(css, /\.sort-option \{[^}]*text-align: left/);
assert.match(js, /function setSortMenuOpen\(/);
assert.match(js, /data-sort/);
assert.match(html, /data-sort="recent"><span>Recent<\/span>/);
assert.match(js, /approvedList\.setSort\(sortValue\)/);
assert.doesNotMatch(html, /<select id="clientSelect"/);
assert.match(html, /id="clientSelect"[^>]*aria-haspopup="listbox"[^>]*aria-expanded="false"/);
assert.match(html, /id="clientSelect"[^>]*aria-labelledby="workspaceLabel clientSelectLabel"/);
assert.match(html, /id="clientMenu"[^>]*role="listbox"/);
assert.match(css, /\.client-select \{[^}]*height: var\(--control-height\)/);
assert.match(html, /class="client-chevron"[^>]*>▼</);
assert.match(css, /\.client-select-label \{[^}]*position: absolute[^}]*left: 10px/);
assert.match(css, /\.client-chevron \{[^}]*position: absolute[^}]*right: 10px/);
assert.match(css, /\.client-control \{[^}]*height: var\(--control-height\)/);
assert.match(css, /\.client-control \{[^}]*z-index: 40/);
assert.match(css, /\.client-menu \{[^}]*position: absolute[^}]*top: calc\(100% \+ 5px\)/);
assert.match(css, /\.client-menu \{[^}]*background: var\(--surface-raised\)/);
assert.match(css, /\.client-bar \{[^}]*z-index: 30/);
assert.match(css, /\.busy-overlay \{[^}]*z-index: 100/);
assert.match(css, /\.client-option \{[^}]*text-align: left/);
assert.match(js, /function setClientMenuOpen\(/);
assert.match(js, /data-client-id/);
assert.match(js, /tabindex=\\"0\\"/);
assert.match(js, /return "<div tabindex=\\"0\\" class=\\"client-option/);
assert.doesNotMatch(js, /return "<button[^"]*client-option/);
assert.match(js, /function chooseClientOption\([^)]*\)[\s\S]*selectClient\(clientId\)/);
assert.match(js, /case "ArrowDown"/);
assert.match(js, /case "Escape"/);
assert.match(js, /case "Tab":[\s\S]*event\.preventDefault\(\)[\s\S]*setClientMenuOpen\(false\)[\s\S]*tabTarget\.focus\(\)/);
assert.match(js, /case "Tab":[\s\S]*event\.preventDefault\(\)[\s\S]*setSortMenuOpen\(false\)[\s\S]*sortTabTarget\.focus\(\)/);
assert.match(css, /scrollbar-width: thin/);
assert.doesNotMatch(html, /id="filterChanges"/);
assert.doesNotMatch(js, /textContent = swatches \? "Swatches"/);
assert.match(html, /id="showApprovedButton" class="library-tab is-active" role="button" tabindex="0"/);
assert.match(html, /id="showSwatchesButton" class="library-tab" role="button" tabindex="0"/);
assert.match(css, /\.library-tab\.is-active, \.filter-tab\.is-active \{[^}]*background: var\(--surface-hover\)[^}]*color: var\(--text\)/);
assert.match(css, /\.filter-tab \{[^}]*white-space: nowrap/);
assert.match(css, /\.filter-tab \{[^}]*min-width: max-content/);
assert.match(js, /pageSize: 0/);
assert.doesNotMatch(html, /Show more/);
assert.doesNotMatch(html, /loadMoreButton/);
assert.doesNotMatch(js, /loadMoreButton/);
assert.match(html, /id="swatchWorkspace"/);
assert.match(html, /id="swatchStatus"/);
assert.match(html, /id="retrySwatchesButton"/);
assert.match(html, /id="swatchDetail"/);
assert.match(html, /id="openSwatchButton"/);
assert.match(html, /id="copyHexButton"[^>]*>Copy</);
assert.match(html, /id="swatchCodeRow"/);
assert.match(manifest, /"clipboard": "readAndWrite"/);
assert.match(js, /api\.setContent\(\{ "text\/plain": text \}\)/);
assert.match(js, /api\.writeText\(text\)/);
assert.match(js, /legacy\.copyText\(text\)/);
assert.match(js, /document\.execCommand\("copy"\)/);
assert.match(js, /await writeClipboardText\(hex\)/);
assert.match(js, /textContent = "Copied"/);
assert.match(js, /Could not copy hex\./);
assert.match(js, /resetCopyHexButton\(false\)/);
assert.match(css, /\.copy-hex:focus-visible \{[^}]*outline: 2px solid var\(--brand\)/);
assert.match(css, /\.copy-hex\.is-copied \{[^}]*color: var\(--success\)/);
assert.match(css, /\.copy-hex:disabled \{[^}]*opacity: \.6/);
assert.match(js, /\/api\/plugin\/swatches/);
assert.match(js, /Could not load swatches/);
assert.match(js, /No swatches yet/);
assert.match(js, /No matches/);
assert.match(css, /\.library-switch/);
assert.match(css, /\.swatch-stage/);
assert.match(html, /class="refresh-glyph"/);
assert.match(html, /class="back-glyph"/);
assert.match(html, />Back</);
assert.doesNotMatch(html, /<svg/);
assert.match(html, /<div class="app-shell">[\s\S]*id="detailPanel"[\s\S]*<\/aside>\s*<\/div>/);

assert.match(css, /\.favorite-button \.star-glyph \{[^}]*left: -1px/);
assert.match(js, /☆/);
assert.match(js, /★/);
assert.match(js, /class=\\"saved-chip\\">Saved/);
assert.match(js, /class=\\"saved-label\\">Saved/);
assert.match(js, /class=\\"reference-item\\"/);
assert.match(js, /class=\\"open-hint\\">Open</);
assert.match(js, /querySelectorAll\("\.reference-item"\)/);
assert.match(js, /classList\.add\("is-detail"\)/);
assert.doesNotMatch(js, /Open in Photoshop/);
assert.doesNotMatch(js, /<svg/);
assert.doesNotMatch(js, /app-shell"\)\.classList\.add\("is-hidden"\)/);

assert.match(css, /\.app-shell\.is-detail \.client-bar/);
assert.match(css, /\.reference-item:hover \.open-hint/);
assert.match(css, /\.reference-preview img\.is-ready:not\(\.is-broken\) \+ \.thumb-fallback/);
assert.match(js, /createPreviewLoader/);
assert.match(js, /previewFileUrl/);
assert.match(js, /fillPreviews/);
assert.match(js, /data-preview-id/);
assert.match(js, /has-preview/);
assert.match(js, /thumb-spinner/);
assert.match(js, /is-loading/);
assert.match(css, /\.thumb-wrap\.has-preview \.thumb-fallback/);
assert.match(css, /\.thumb-wrap\.is-loading \.thumb-spinner/);
assert.match(html, /id="busyOverlay" class="busy-overlay"/);
assert.doesNotMatch(html, /id="busyOverlay"[^>]*is-hidden/);
assert.match(css, /\.busy-overlay \{/);
assert.match(fs.readFileSync("UXP/preview-data.js", "utf8"), /getBytes\("\/api\/plugin\/versions\/" \+ encodeURIComponent\(item\.versionId\) \+ "\/preview"\)/);
assert.doesNotMatch(js, /host \+ "\/api\/plugin\/versions\//);
assert.doesNotMatch(js, /escapeHtml\(ref\.fsUrl\)/);
assert.match(css, /\.back-button \{[^}]*width: auto/);

const uxpReadme = fs.readFileSync("UXP/README.md", "utf8");
const rootReadme = fs.readFileSync("README.md", "utf8");
assert.match(uxpReadme, /UnifiedPluginInstallerAgent\.exe \/install/);
assert.match(uxpReadme, /Plugins → Pixofix Color Library/);
assert.doesNotMatch(uxpReadme, /PLUGIN_ACCESS_KEY/);
assert.doesNotMatch(rootReadme, /PLUGIN_ACCESS_KEY/);
assert.match(uxpReadme, /v0\.5\.11/);
assert.match(uxpReadme, /This package is `0\.5\.11`/);
assert.match(uxpReadme, /spinner instead of a letter/);
assert.match(uxpReadme, /JSON and preview fetches wait 8s/);
assert.match(rootReadme, /0\.5\.11/);
assert.match(rootReadme, /spinner instead of a letter/);
const floor = uxpReadme.slice(uxpReadme.indexOf("## Floor install"), uxpReadme.indexOf("## Development load"));
assert.doesNotMatch(floor, /UXP Developer Tool/);

console.log("Panel UI tests passed.");
