const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { cssColorKeywords, cssColorEntries, nameForHex, suggestedNameForHex } = require("../server/css-color-names");
const { pluginSwatchJson } = require("../server/pixofix-library");
const { pool } = require("../server/db");

const root = path.resolve(__dirname, "..");
const read = relative => fs.readFileSync(path.join(root, relative), "utf8");

assert.strictEqual(cssColorKeywords().length, 148);
assert.strictEqual(cssColorEntries().length, 139);
assert.strictEqual(new Set(cssColorKeywords().map(item => item.hexCode)).size, 139);
assert.strictEqual(nameForHex("#FF0000"), "Red");
assert.strictEqual(nameForHex("#f00"), "Red");
assert.strictEqual(nameForHex("  #808080 "), "Gray");
assert.strictEqual(nameForHex("#00ffff"), "Aqua");
assert.strictEqual(nameForHex("#ff00ff"), "Fuchsia");
assert.strictEqual(nameForHex("#abc"), "#AABBCC");
assert.strictEqual(nameForHex("#AB274F"), "#AB274F");
assert.strictEqual(nameForHex("#DE3163"), "#DE3163");
assert.strictEqual(nameForHex("#800020"), "#800020");
assert.strictEqual(nameForHex("red"), "");
assert.strictEqual(nameForHex("#12345"), "");
assert.strictEqual(nameForHex(""), "");
for (const entry of cssColorEntries()) {
  assert.strictEqual(suggestedNameForHex(entry.hexCode), entry.name);
}
assert.strictEqual(suggestedNameForHex("#E76223"), "Persimmon");
assert.strictEqual(suggestedNameForHex("#AB274F"), "Amaranth Purple");
assert.strictEqual(suggestedNameForHex("#010101"), "Black");
assert.strictEqual(suggestedNameForHex("#DE3163"), "Cerise");
assert.strictEqual(suggestedNameForHex("#de3163"), "Cerise");
assert.strictEqual(suggestedNameForHex("#DE3164"), "Cerise");
assert.strictEqual(suggestedNameForHex("#800020"), "Burgundy");
assert.strictEqual(suggestedNameForHex("#800021"), "Burgundy");
assert.strictEqual(suggestedNameForHex("#882D17"), "Sienna");
assert.strictEqual(suggestedNameForHex("#E34234"), "Vermilion");
assert.strictEqual(suggestedNameForHex("red"), "");
assert.strictEqual(suggestedNameForHex(""), "");

const grey = cssColorKeywords().find(item => item.keyword === "grey");
assert.strictEqual(grey.name, "Gray");
assert.strictEqual(cssColorEntries().find(item => item.hexCode === grey.hexCode).name, "Gray");

const library = read("server/pixofix-library.js");
const listRoute = library.slice(library.indexOf('app.get("/api/pixofix/colors"'), library.indexOf('app.get("/api/pixofix/colors/:id/swatch"'));
const createRoute = library.slice(library.indexOf('app.post("/api/pixofix/colors"'), library.indexOf('app.post("/api/pixofix/colors/:id/save"'));
assert.match(listRoute, /requireRole\("CLIENT", "ADMIN"\)/);
assert.match(library.slice(library.indexOf('app.get("/api/pixofix/colors/:id/swatch"'), library.indexOf('app.post("/api/pixofix/colors"')), /requireRole\("CLIENT", "ADMIN"\)/);
assert.match(createRoute, /requireRole\("ADMIN"\)/);
assert.doesNotMatch(createRoute, /requireRole\("CLIENT"/);
assert.match(createRoute, /clientId: null/);
assert.match(createRoute, /entityType: "pixofix_color"/);
assert.match(createRoute, /Enter a valid hex code/);
assert.match(createRoute, /Color name is required/);
assert.match(createRoute, /colorNameFromBody/);
assert.match(library, /if \(value == null\) return nameForHex\(hexCode\)/);
assert.match(library, /String\(value\)\.trim\(\)\.slice\(0, 120\)/);
assert.match(createRoute, /This hex is already in Explore swatches/);
const nameRoute = library.slice(library.indexOf('app.get("/api/pixofix/color-name"'), library.indexOf('app.post("/api/pixofix/colors"'));
assert.match(nameRoute, /requireRole\("CLIENT", "ADMIN"\)/);
assert.match(nameRoute, /suggestedNameForHex/);
assert.match(listRoute, /pixofix_saves/);
const saveRoute = library.slice(library.indexOf('app.post("/api/pixofix/colors/:id/save"'), library.indexOf('app.post("/api/pixofix/colors/:id/delete"'));
assert.match(saveRoute, /requireRole\("CLIENT", "ADMIN"\)/);
assert.match(saveRoute, /Choose whether to save this swatch/);
assert.doesNotMatch(saveRoute, /writeAudit/);
const deleteRoute = library.slice(library.indexOf('app.post("/api/pixofix/colors/:id/delete"'), library.indexOf("function colorNameFromBody"));
assert.match(deleteRoute, /requireRole\("ADMIN"\)/);
assert.doesNotMatch(deleteRoute, /requireRole\("CLIENT"/);
assert.match(deleteRoute, /Type delete to confirm/);
assert.match(deleteRoute, /action: "DELETE"/);
assert.match(read("database/012_pixofix_saves.sql"), /CREATE TABLE IF NOT EXISTS pixofix_saves/);
assert.match(read("database/012_pixofix_saves.sql"), /REFERENCES pixofix_colors/);
assert.match(read("server/index.js"), /registerPixofixLibrary/);
assert.match(read("scripts/migrate.js"), /seedPixofixColors/);
assert.match(read("database/010_pixofix_colors.sql"), /CREATE TABLE IF NOT EXISTS pixofix_colors/);
assert.doesNotMatch(library, /coolors/i);

const portal = read("public/app.js");
const page = read("public/pixofix-library.js");
assert.match(portal, /state\.view==="pixofix"/);
assert.match(portal, /id:"pixofix",label:"Explore swatches"/);
assert.match(page, /state\.user\.role === "ADMIN" \? '<button id="addPixofixColor"/);
assert.match(page, /Color name/);
assert.match(page, /name="name"/);
assert.match(page, /bindPixofixColorName/);
assert.match(page, /removeEventListener\("submit", pixofixSubmitGuard, true\)/);
assert.match(page, /event\.currentTarget\?\.querySelector\('\[name="hexCode"\]'\)/);
assert.match(page, /\/api\/pixofix\/color-name/);
assert.match(page, /Could not suggest a name/);
assert.match(page, /Suggested in Adobe RGB \(1998\)/);
assert.doesNotMatch(page, /closest CSS color/);
assert.match(page, /name="hexCode"[\s\S]{0,500}id="pixofixExists"/);
assert.match(page, /This color already exists\./);
assert.doesNotMatch(page, /\$\{existing\.name\} is already in Explore swatches/);
assert.match(page, /Checking Explore swatches/);
assert.match(page, /Could not check whether this color is already in Explore swatches/);
assert.match(page, /pixofixNormalizeHex/);
assert.match(page, /state\.pixofixColors\.find/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-exists/);
assert.match(page, /const name = String\(form\.get\("name"\) \|\| ""\)\.trim\(\)/);
assert.match(page, /JSON\.stringify\(\{ hexCode, name \}\)/);
assert.doesNotMatch(page, /Otherwise the name is the hex/);
assert.match(page, /Loading swatches/);
assert.match(page, /Could not load swatches/);
assert.match(page, /No swatches yet/);
assert.match(page, /Clear search/);
assert.match(page, /Show all colors/);
assert.match(page, /shadeFiltersMarkup\(shade\)/);
assert.match(page, /pixofix-controls/);
assert.match(page, /clearPixofixFilters/);
assert.match(read("public/app.js"), /is-pixofix/);
assert.match(read("public/pixofix-library.css"), /grid-template-columns:\s*repeat\(6,\s*max-content\)/);
assert.match(read("public/pixofix-library.css"), /@keyframes pixofix-chip-in/);
assert.match(read("public/pixofix-library.css"), /translate:\s*16px 0/);
assert.match(read("public/pixofix-library.css"), /prefers-reduced-motion:\s*reduce/);
assert.match(page, /shadeIdForColor\(color\)/);
assert.doesNotMatch(read("public/app.js"), /shadeFiltersMarkup|shadeIdForColor|libraryShade/);
assert.match(read("public/index.html"), /color-shades\.js/);
assert.match(page, /Copy hex/);
assert.match(page, /pixofix-hex-copy/);
assert.doesNotMatch(page, />Copy hex<\/button>/);
assert.match(page, /pixofix-spec/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-facts \{[\s\S]*grid-template-columns: minmax\(0, 1\.15fr\) minmax\(0, 1\.35fr\) minmax\(0, 0\.9fr\)/);
assert.match(read("public/pixofix-library.css"), /\.page\.is-index:has\(\.pixofix-detail\) \{[\s\S]*100dvh/);
assert.match(read("public/pixofix-library.css"), /\.page\.is-index:has\(\.pixofix-detail\) \.content \{[\s\S]*overflow: hidden/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-spec \.pixofix-request-color \{[\s\S]*grid-row: 3/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-spec \.pixofix-request-color \{[\s\S]*width: 100%/);
assert.match(page, /More \$\{esc\(label\)\}/);
assert.match(page, /Closest Adobe RGB matches\./);
assert.doesNotMatch(page, /matches in this family/);
assert.match(page, /pixofixDistance/);
assert.match(page, /bindPixofixPreview/);
assert.match(page, /pixofix-preview-label/);
assert.match(read("public/pixofix-library.css"), /@keyframes pixofix-stage-opacity/);
assert.match(read("public/pixofix-library.css"), /21% \{ opacity: 1; \}/);
assert.match(read("public/pixofix-library.css"), /translate: 0px 16px/);
assert.match(read("public/pixofix-library.css"), /scale: 0\.96 0\.96/);
assert.match(read("public/pixofix-library.css"), /@keyframes pixofix-related-in/);
assert.match(page, /pixofixRgb/);
assert.match(page, /<dt>Adobe RGB<\/dt>/);
assert.match(page, /<dt>Profile<\/dt>/);
assert.match(page, /adobeRgbCss/);
assert.match(read("public/adobe-rgb.js"), /color\(a98-rgb /);
assert.match(page, /swatch"}\.png/);
assert.match(read("public/index.html"), /adobe-rgb\.js/);
assert.ok(read("public/index.html").indexOf("adobe-rgb.js") < read("public/index.html").indexOf("pixofix-library.js"));
assert.match(library, /image\/png/);
assert.match(library, /adobe-rgb-1998/);
assert.match(library, /profile: ADOBE_RGB_NAME/);
assert.match(page, /data-pixofix-copy/);
assert.match(page, /data-pixofix-download/);
assert.match(page, /Could not download this swatch/);
assert.match(page, /pixofix-stage-title-row/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-stage \.pixofix-action \{\s*position: relative;/);
assert.match(page, /data-pixofix-save/);
assert.match(page, /data-pixofix-delete/);
assert.match(page, /pixofix-action-label/);
assert.match(page, /id="deletePixofixColor"/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-delete-swatch \{\s*position: absolute;\s*top: 18px;\s*right: 18px;/);
assert.match(page, /Delete swatch/);
assert.match(page, /Deleting…/);
assert.doesNotMatch(page, /pixofix-action pixofix-delete/);
assert.match(page, /class="pixofix-action pixofix-copy"[\s\S]*class="pixofix-action pixofix-save"/);
assert.match(page, /Number\(Boolean\(b\.saved\)\) - Number\(Boolean\(a\.saved\)\)/);
const saveHandler = page.slice(page.indexOf("async function togglePixofixSave"), page.indexOf("async function deletePixofixColor"));
assert.doesNotMatch(saveHandler, /drawPixofixColors\(/);
assert.match(saveHandler, /reorderPixofixCards\(/);
assert.match(saveHandler, /paintPixofixSaved\(/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-grid\.is-settled \.pixofix-card \{\s*animation: none;/);
assert.match(page, /Could not save this swatch/);
assert.match(page, /Could not delete this swatch/);
assert.match(read("public/pixofix-library.css"), /radial-gradient\(circle, rgba\(17, 17, 17, \.38\)/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-copy \{\s*right: 34px;/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-action \.pixofix-copied-glyph \{\s*display: none;/);
assert.doesNotMatch(read("public/pixofix-library.css"), /\.pixofix-delete \{\s*position: absolute;\s*top: 8px;/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-save\[aria-pressed="true"\]/);
assert.match(page, /is-saved/);
assert.match(read("public/pixofix-library.css"), /#f0c14b/);
assert.doesNotMatch(read("public/pixofix-library.css"), /\.pixofix-copy \{\s*position: absolute/);
assert.match(page, /pixofix-swatch/);
assert.match(page, /class="pixofix-hex-label"/);
assert.match(page, /placeholder="Search hex"/);
assert.match(page, /pixofix-action-label">Copy hex</);
assert.match(read("public/pixofix-library.css"), /\.pixofix-hex-label \{[^}]*opacity: 0;/);
assert.match(read("public/pixofix-library.css"), /\.pixofix-card:hover \.pixofix-hex-label,\s*\.pixofix-card:focus-within \.pixofix-hex-label \{ opacity: 1; \}/);
assert.match(read("public/pixofix-library.css"), /grid-template-columns:\s*repeat\(6,/);
assert.match(read("public/tokens.css"), /--card-name-vignette:\s*linear-gradient\(to top, rgba\(0, 0, 0, \.6\) 0%, rgba\(0, 0, 0, \.28\) 36%, rgba\(0, 0, 0, \.08\) 68%, transparent 100%\)/);
assert.match(read("public/pixofix-library.css"), /background:\s*var\(--card-name-vignette\)/);
assert.match(read("public/color-details.css"), /background:\s*var\(--card-name-vignette\)/);
assert.match(read("public/color-details.css"), /\.library-color-card \.card-head \{ align-items: center;[^}]*padding: 42%/);
assert.doesNotMatch(page, /pixofix-card-copy/);
assert.doesNotMatch(page.replaceAll("/api/pixofix/colors/", ""), /\/colors\//);
assert.match(read("public/index.html"), /pixofix-library\.js/);
assert.match(read("public/index.html"), /pixofix-library\.css/);

const pluginList = library.slice(library.indexOf('app.get("/api/plugin/swatches"'), library.indexOf('app.get("/api/plugin/swatches/:id/image"'));
const pluginImage = library.slice(library.indexOf('app.get("/api/plugin/swatches/:id/image"'), library.indexOf('app.get("/api/pixofix/colors"'));
assert.doesNotMatch(pluginList, /requireLocalPlugin/);
assert.match(pluginList, /pluginSwatchJson/);
assert.doesNotMatch(pluginList, /pixofix_saves|requireRole/);
assert.doesNotMatch(pluginImage, /requireLocalPlugin/);
assert.match(pluginImage, /ensureSwatch/);
const pluginSwatch = pluginSwatchJson({ id: "swatch-1", hex_code: "#800000", name: "Maroon" });
assert.deepStrictEqual(pluginSwatch, { id: "swatch-1", hexCode: "#800000", name: "Maroon", shade: "red" });
assert.equal(pluginSwatch.saved, undefined);

console.log("Explore swatches tests passed.");
pool.end();
